project:
  type: website
  output-dir: docs

website:
  title: "Análisis de la Variancia (ANOVA)"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: journal
    lang: es
